# Generated by Django 3.2.4 on 2021-07-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210719_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_verfy',
            new_name='is_verify',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school_id',
        ),
        migrations.AddField(
            model_name='driver',
            name='card_owner',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
